Project
{
    _main_()
    {
        # calculator 已从 ConsoleTest.fun() 中注释掉（交互式阻塞 stdin），可在此单独调用
        CsvTest.fun();
        #LinkedListTest.fun()
        #!
        CsvTest.fun()
        ListTest.fun()
        MapTest.fun()
        FileTest.fun()
        DirectoryTest.fun()
       #ConsoleTest.fun()
        DateTimeTest.fun()
        Sqlite3Test.fun()
        !#
    }
    CompileBefore()
    {
    }
    CompileAfter()
    {
    }
}
